### ISSUE TITLE
Quote characters are escaped with backslash (Magic Quotes)

### ISSUE THREAD

**Issue by pmer** [savetheinternet/Tinyboard#6] opened 2010-11-02 15:02 UTC
**ISSUE**

Quote characters ( ' and " but not ` ) in the email, subject, or comment boxes are prefixed with with a backslash ( \ ). The name box is unaffected. 

While it may be fine in code, this is the wrong way to escape text in HTML.

**REPRODUCTION**

Make a topic or reply containing a quote character in the email, subject, or comment box.

**EXPECTED RESULT**

The quote character will be properly escaped for HTML.

**Comment by savetheinternet** [comment] 2010-11-02 21:40
This is caused by magic_quotes_gpc being enabled in your PHP configuration.

Magic Quotes is a process that automagically escapes incoming data to the PHP script. It's preferred to code with magic quotes off and to instead escape the data at runtime, as needed.

Although it is a bad practice to use magic quotes and it has been deprecated as of PHP 5.3.0, I will add a check for magic quotes and 'undo' it at runtime.

http://php.net/manual/en/security.magicquotes.php

**Comment by savetheinternet** [comment] 2010-11-03 05:06
Fixed in commit 7181634dcbeaba0375e91237f285f619e510bf65

**Closed as completed by savetheinternet** 2010-11-03 05:06 UTC
