### ISSUE TITLE
Cannot Run Install.php

### ISSUE THREAD

**Issue by zifaun** [savetheinternet/Tinyboard#117] opened 2013-06-24 16:43 UTC
Hi, I have the latest version of Tinyboard uploaded to my web host (as of 6/24/13). When I run the install.php, I get the following error:

Server error
The website encountered an error while retrieving http://xxxxxx.com/imageboards/w/install.php. It may be down for maintenance or configured incorrectly.
Here are some suggestions:
Reload this webpage later.
HTTP Error 500 (Internal Server Error): An unexpected condition was encountered while the server was attempting to fulfill the request.

The error_log it generates says the following:

[24-Jun-2013 10:41:34] PHP Parse error:  syntax error, unexpected T_FUNCTION in /xxxxxxxx/public_html/imageboards/w/inc/display.php on line 232

**Comment by savetheinternet** [comment] 2013-06-24 18:01
What PHP version are you using?

**Comment by zifaun** [comment] 2013-06-24 21:12
My website is being hosted by JustHost. According to their site they are using PHP 5.
http://justhost.com/cgi/info/hosting_features

**Comment by czaks** [comment] 2013-07-08 15:11
This is duplicate of #120

**Comment by savetheinternet** [comment] 2013-07-08 16:28
> My website is being hosted by JustHost. According to their site they are using PHP 5.

"PHP 5" isn't specific enough.

Closing due to likely duplicate.

**Closed as completed** 2013-07-08 16:28 UTC
